M48
; DRILL file {KiCad 9.0.7+dfsg-1} date 2026-03-28T18:55:19+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-28T18:55:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X131.0Y-70.0
X131.0Y-106.0
X138.0Y-106.0
X185.0Y-70.0
X192.0Y-70.0
X192.0Y-106.0
M30
