M48
; DRILL file {KiCad 9.0.7+dfsg-1} date 2026-03-28T18:53:45+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-28T18:53:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.854
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X160.944Y-38.151
X160.944Y-40.651
T2
X77.0Y-38.0
X77.0Y-74.0
X84.0Y-38.0
X131.0Y-74.0
X138.0Y-38.0
X138.0Y-74.0
M30
